<?php /** @var \Viacheslav\RegularCustomer\Block\Product\View\PersonalDiscount $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div data-bind="scope: 'loyaltyProgramButton'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "loyaltyProgramButton": {
                        "component": "ViacheslavRegularCustomerButton",
                        "productId": <?= (int) $block->getProduct()->getId() ?>
                    }
                }
            }
        }
    }
</script>
